apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ..............dkr.ecr.us-east-1.amazonaws.com/mern-instagram-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: AWS_ACCESS_KEY
              value: ".........."
            - name: AWS_SECRET_KEY
              value: "............."
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_BUCKET_NAME
              value: "mern-instagram-media-123745-bucket"  
            - name: MONGO_URI
              value: "mongodb+.............."
            - name: JWT_SECRET
              value: "..............."
            - name: PORT
              value: "5000"